---
AWSTemplateFormatVersion: 2010-09-09
Description: EC2 instance with a single network interface and multiple static IP addresses
Parameters:
  ImageId:
    Description: Set an EC2 AMI ID.
    Type: AWS::EC2::Image::Id
    ConstraintDescription: must be a valid EC2 instance type.
  InstanceType:
    Description: Set an EC2 instance type.
    Type: String
    Default: t2.micro
    ConstraintDescription: must be a valid EC2 instance type.
  InstanceName:
    Description: Set an EC2 instance name.
    Type: String
    Default: headnode
  EbsVolumeSize:
    Description: Set EBS volume size.
    Type: Number
    MinValue: 0
    Default: 30
  VpcId:
    Description: Set the VpcId of an existing VPC.
    Type: AWS::EC2::VPC::Id
    ConstraintDescription: must be the VPC Id of an existing Virtual Private Cloud.
  SubnetId:
    Description: Set the SubnetId of an existing subnet (for the primary network) in the VPC.
    Type: AWS::EC2::Subnet::Id
    ConstraintDescription: must be an existing subnet in the selected Virtual Private Cloud.
Resources:
  EC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: !Ref ImageId
      InstanceType: !Ref InstanceType
      NetworkInterfaces:
        - DeviceIndex: 0
          NetworkInterfaceId: !Ref EC2NetworkInterface
      BlockDeviceMappings:
        - DeviceName: /dev/xvda
          Ebs:
            VolumeSize: !Ref EbsVolumeSize
            VolumeType: gp3
            Encrypted: true
            DeleteOnTermination: true
      InstanceInitiatedShutdownBehavior: terminate
      IamInstanceProfile: !Ref EC2InstanceProfile
      Tags:
        - Key: Name
          Value: !Ref InstanceName
  EC2SecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      VpcId: !Ref VpcId
      GroupName: !Sub ${InstanceName}-security-group
      GroupDescription: EC2 security group
      Tags:
        - Key: Name
          Value: !Sub ${InstanceName}-security-group
  SSMInterfaceEndpoint:
    Type: AWS::EC2::VPCEndpoint
    Properties:
      PrivateDnsEnabled: true
      SubnetIds:
        - !Ref SubnetId
      SecurityGroupIds:
        - !Ref EC2SecurityGroup
      ServiceName: !Sub com.amazonaws.${AWS::Region}.ssm
      VpcEndpointType: Interface
      VpcId: !Ref VpcId
  SSMMessagesInterfaceEndpoint:
    Type: AWS::EC2::VPCEndpoint
    Properties:
      PrivateDnsEnabled: true
      SubnetIds:
        - !Ref SubnetId
      SecurityGroupIds:
        - !Ref EC2SecurityGroup
      ServiceName: !Sub com.amazonaws.${AWS::Region}.ssmmessages
      VpcEndpointType: Interface
      VpcId: !Ref VpcId
  EC2MessagesInterfaceEndpoint:
    Type: AWS::EC2::VPCEndpoint
    Properties:
      PrivateDnsEnabled: true
      SubnetIds:
        - !Ref SubnetId
      SecurityGroupIds:
        - !Ref EC2SecurityGroup
      ServiceName: !Sub com.amazonaws.${AWS::Region}.ec2messages
      VpcEndpointType: Interface
      VpcId: !Ref VpcId
  EC2NetworkInterface:
    Type: AWS::EC2::NetworkInterface
    Properties:
      GroupSet:
        - !Ref EC2SecurityGroup
      SourceDestCheck: false
      SubnetId: !Ref SubnetId
  EC2EIP:
    Type: AWS::EC2::EIP
    Properties:
      Domain: vpc
  EC2EIPAssociation:
    Type: AWS::EC2::EIPAssociation
    Properties:
      AllocationId: !GetAtt EC2EIP.AllocationId
      InstanceId: !Ref EC2Instance
  EC2InstanceRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub ${InstanceName}-EC2InstanceRole
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - ec2.amazonaws.com
                - ssm.amazonaws.com
            Action:
              - sts:AssumeRole
      Path: /
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore
  EC2InstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Path: /
      Roles:
        - !Ref EC2InstanceRole
Outputs:
  EC2InstanceId:
    Description: EC2 Instance Id
    Value: !Ref EC2Instance
    Export:
      Name: !Sub ${AWS::Region}-${AWS::StackName}-EC2InstanceId
  EC2InstanceEIP:
    Description: Primary public IP of network interface
    Value: !Ref EC2EIP
    Export:
      Name: !Sub ${AWS::Region}-${AWS::StackName}-EC2InstanceEIP
